package com.abhilash.fleetmanagement.dao;

import com.abhilash.fleetmanagement.model.Tires;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.Instant;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@ApiModel(value = "Reading", description = "Class representing a reading generated by the sensors (mock)")
public class ReadingDao {
    @ApiModelProperty(notes = "Vehicle Identifier (unique)", example = "1FMYU02143KB34432", required = true, position = 0)
    private String vin;
    @ApiModelProperty(notes = "Latitude value of the truck's location", example = "41.803194", required = true, position = 1)
    private double latitude;
    @ApiModelProperty(notes = "Longitude value of the truck's location", example = "-88.144406", required = true, position = 2)
    private double longitude;
    @ApiModelProperty(notes = "The time at which the reading was taken", example = "2019-02-10T03:04:33Z", required = true, position = 3)
    private Instant timestamp;
    @ApiModelProperty(notes = "vehicle's current fuel volume as measured by the sensors (mock)", example = "1.5", required = true, position = 4)
    private double fuelVolume;
    @ApiModelProperty(notes = "vehicle's current speed as measured by the sensors (mock)", example = "85", required = true, position = 5)
    private int speed;
    @ApiModelProperty(notes = "vehicle's current engine HP as measured by the sensors (mock)", example = "240", required = true, position = 6)
    private int engineHp;
    @ApiModelProperty(notes = "True if engine check light is ON else False as measured by the sensors (mock)", example = "true", required = true, position = 7)
    private boolean checkEngineLightOn;
    @ApiModelProperty(notes = "True if engine coolant is low else False as measured by the sensors (mock)", example = "false", required = true, position = 7)
    private boolean engineCoolantLow;
    @ApiModelProperty(notes = "True if Cruise Control is ON else False as measured by the sensors (mock)", example = "false", required = true, position = 7)
    private boolean cruiseControlOn;
    @ApiModelProperty(notes = "vehicle's current engine RPM as measured by the sensors (mock)", example = "6300", required = true, position = 10)
    private int engineRpm;
    @ApiModelProperty(notes = "Vehicle's Tyre pressure measurements in PSI as measured by sensors (mock)", required = true, position = 11)
    private Tires tires;
}
